# [package]
# name = "nmbrs"
# version = "0.1.0"
# edition = "2021"
# authors = ["sweil"]

[workspace]
members = [ "libs/nmbrs_algebra", "libs/nmbrs_statistics", "libs/nmbrs_optimization", "libs/nmbrs_dynamical_systems" ]